server:
  port: 8083

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/step
  username: step
  password: 1234
  platform: postgres
  driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: resources/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret-key: jwtPractice
  #    //30days
  token:
    expired-time-ms: 60000