spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  properties.hibernate.format_sql: true
  show-sql: true
spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://127.0.0.1:5432/step
  username: root
  password: 1234
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: jwtPractice
  #    //30days
  token:
    expired-time-ms: 60000